#ifndef _STK_PARAMETERS_H
#define _STK_PARAMETERS_H

/*

STKEngine2

Copyright 2016-2022 Pete Goodwin

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Note this only applies to STKEngine2 and not the STK software itself.
*/

enum STK_OSC_TYPE
{
	STK_OSC_TYPE_NONE,
	STK_OSC_TYPE_SAW,
	STK_OSC_TYPE_SQUARE,
	STK_OSC_TYPE_SINE,
	STK_OSC_TYPE_NOISE
};

enum STK_PARAMETERS
{
	STK_PARAMETER_MOD_SPEED = 0,
	STK_PARAMETER_MOD_DEPTH,

	STK_PARAMETER_OSC1_TYPE = 0,
	STK_PARAMETER_OSC1_GAIN,
	STK_PARAMETER_OSC1_COARSE,
	STK_PARAMETER_OSC1_FINE,

	STK_PARAMETER_OSC2_TYPE,
	STK_PARAMETER_OSC2_GAIN,
	STK_PARAMETER_OSC2_COARSE,
	STK_PARAMETER_OSC2_FINE,

	STK_PARAMETER_OSC3_TYPE,
	STK_PARAMETER_OSC3_GAIN,
	STK_PARAMETER_OSC3_COARSE,
	STK_PARAMETER_OSC3_FINE,

	STK_FILTER_TYPE,
	STK_FILTER_CUTOFF,
	STK_FILTER_RES,

	STK_AMP_ENVELOPE_ATTACK,
	STK_AMP_ENVELOPE_DECAY,
	STK_AMP_ENVELOPE_SUSTAIN,
	STK_AMP_ENVELOPE_RELEASE,

	STK_FILTER_ENVELOPE_ATTACK,
	STK_FILTER_ENVELOPE_DECAY,
	STK_FILTER_ENVELOPE_SUSTAIN,
	STK_FILTER_ENVELOPE_RELEASE,
	STK_FILTER_ENVELOPE_MIX,

	STK_PARAMETER_LEFT,
	STK_PARAMETER_RIGHT,

	STK_PARAMETER_PANNING,

	STK_REVERB_MIX,

	STK_PARAMETERS_MAX
};

enum STK_EFFECT_PARAMETERS
{
	STK_EFFECT_BYPASS,

	STK_EFFECT_MIX = 1,
	STK_EFFECT_DELAY,
	STK_EFFECT_FEEDBACK,
	STK_EFFECT_PINGPONG,

	STK_EFFECT_MOD_DEPTH = 1,
	STK_EFFECT_MOD_FREQ,

	STK_EFFECT_MAX = 5
};

#endif // _STK_PARAMETERS_H
