#ifndef _STK_PARAMETERS_H
#define _STK_PARAMETERS_H

enum STK_OSC_TYPE
{
	STK_OSC_TYPE_NONE,
	STK_OSC_TYPE_SAW,
	STK_OSC_TYPE_SQUARE,
	STK_OSC_TYPE_SINE,
	STK_OSC_TYPE_NOISE
};

enum STK_PARAMETERS
{
	STK_PARAMETER_MOD_SPEED = 0,
	STK_PARAMETER_MOD_DEPTH,

	STK_PARAMETER_OSC1_TYPE = 0,
	STK_PARAMETER_OSC1_GAIN,
	STK_PARAMETER_OSC1_COARSE,
	STK_PARAMETER_OSC1_FINE,

	STK_PARAMETER_OSC2_TYPE,
	STK_PARAMETER_OSC2_GAIN,
	STK_PARAMETER_OSC2_COARSE,
	STK_PARAMETER_OSC2_FINE,

	STK_PARAMETER_OSC3_TYPE,
	STK_PARAMETER_OSC3_GAIN,
	STK_PARAMETER_OSC3_COARSE,
	STK_PARAMETER_OSC3_FINE,

	STK_FILTER_TYPE,
	STK_FILTER_CUTOFF,
	STK_FILTER_RES,

	STK_AMP_ENVELOPE_ATTACK,
	STK_AMP_ENVELOPE_DECAY,
	STK_AMP_ENVELOPE_SUSTAIN,
	STK_AMP_ENVELOPE_RELEASE,

	STK_FILTER_ENVELOPE_ATTACK,
	STK_FILTER_ENVELOPE_DECAY,
	STK_FILTER_ENVELOPE_SUSTAIN,
	STK_FILTER_ENVELOPE_RELEASE,
	STK_FILTER_ENVELOPE_MIX,

	STK_PARAMETER_LEFT,
	STK_PARAMETER_RIGHT,

	STK_PARAMETER_PANNING,

	STK_REVERB_MIX,

	STK_PARAMETERS_MAX
};

enum STK_EFFECT_PARAMETERS
{
	STK_EFFECT_BYPASS,

	STK_EFFECT_MIX = 1,
	STK_EFFECT_DELAY,
	STK_EFFECT_FEEDBACK,
	STK_EFFECT_PINGPONG,

	STK_EFFECT_MOD_DEPTH = 1,
	STK_EFFECT_MOD_FREQ,

	STK_EFFECT_MAX = 5
};

#endif // _STK_PARAMETERS_H
